FROM mageai/mageai:latest

ARG PROJECT_NAME=mage
ARG GOOGLE_PROJECT
ARG USER_CODE_PATH=/home/src/${PROJECT_NAME}

ENV GOOGLE_PROJECT=${GOOGLE_PROJECT}
ENV GCP_BUCKET_NAME=${GOOGLE_PROJECT}-meteorite-landings

# Note: this overwrites the requirements.txt file in your new project on first run.
# You can delete this line for the second run :)
COPY mage ${USER_CODE_PATH}
COPY key/gcp-service-account.json /home/src/personal-gcp.json

RUN pip3 install -r ${USER_CODE_PATH}/requirements.txt
